#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures new Ubuntu machine and add http header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "26i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start